---
name: "Releases"
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  tagged-release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Produce release body
        id: git_log
        uses: beatlabs/release-changelog-action@v0.0.2
        with:
          tag_regex: "v[0-9]+.[0-9]+.[0-9]+$"